"""Define protocol constants and domain separators."""

RSA_KEY_SIZE = 2048
RSA_PUBLIC_EXPONENT = 65537
RSA_SIGNATURE_SIZE = RSA_KEY_SIZE // 8
RSA_PSS_SALT_LENGTH = 32
PROTOCOL_VERSION = 3
PROTOCOL_FIELD_WIDTH = 8
BOOTSTRAP_START_UNIT = 0
BOOTSTRAP_LSB_COUNT = 1
SESSION_KEY_SIZE = 32
AEAD_NONCE_SIZE = 12
GCM_TAG_SIZE = 16
BOOTSTRAP_PREFIX_FORMAT = ">BB"
SUPPORTED_LSB_COUNTS = tuple(range(1, 9))
IMAGE_MEDIA_CODE = 1
AUDIO_MEDIA_CODE = 2
SUPPORTED_MEDIA_CODES = (IMAGE_MEDIA_CODE, AUDIO_MEDIA_CODE)
MEDIA_PREFIXES = {IMAGE_MEDIA_CODE: "IMG", AUDIO_MEDIA_CODE: "AUD"}
MEDIA_ID_SIZE = 36  # Four-byte prefix plus 32 hexadecimal characters.

SHA256_DIGEST_SIZE = 32
MEDIA_HASH_DOMAIN = b"INF2005-ACW1\x00MEDIA-HASH-V3\x00"
SIGNING_DOMAIN = b"INF2005-ACW1\x00SIGN\x00"
MEDIA_HASH_CONTEXT_PREFIX_FORMAT = ">BB"
SIGNING_CONTEXT_PREFIX_FORMAT = ">BBB"

NONCE_SIZE = 16
MAX_MEDIA_ID_BYTES = 255

PNG_CARRIER_MODE = "RGB"
PNG_ALPHA_CARRIER_MODE = "RGBA"
RGB_CHANNEL_COUNT = 3
RGBA_CHANNEL_COUNT = 4
PNG_MEDIA_CONTEXT_FORMAT = ">IIB"
WAV_MEDIA_CONTEXT_FORMAT = ">HBIQ"

FINGERPRINT_DISPLAY_PREFIX = "SHA256:"
