"""Protocol constants and domain separators."""

import struct

RSA_KEY_SIZE = 2048
RSA_PUBLIC_EXPONENT = 65537
RSA_SIGNATURE_SIZE = RSA_KEY_SIZE // 8
RSA_PSS_SALT_LENGTH = 32
PROTOCOL_VERSION = 1
START_MAGIC = bytes.fromhex("d9df721b281169d4335290e30fdb48b1")
SUPPORTED_LSB_COUNTS = tuple(range(1, 9))
IMAGE_MEDIA_CODE = 1
AUDIO_MEDIA_CODE = 2
SUPPORTED_MEDIA_CODES = (IMAGE_MEDIA_CODE, AUDIO_MEDIA_CODE)
MEDIA_PREFIXES = {IMAGE_MEDIA_CODE: "IMG", AUDIO_MEDIA_CODE: "AUD"}

SHA256_DIGEST_SIZE = 32
MEDIA_HASH_DOMAIN = b"INF2005-ACW1\x00MEDIA-HASH\x00"
SIGNING_DOMAIN = b"INF2005-ACW1\x00SIGN\x00"
MEDIA_HASH_CONTEXT_FORMAT = ">BBQQQ"
SIGNING_CONTEXT_FORMAT = ">BBBQQQI"

PACKET_HEADER_FORMAT = ">16sBBBI"
PACKET_HEADER_SIZE = struct.calcsize(PACKET_HEADER_FORMAT)
MAX_PAYLOAD_LENGTH = 16 * 1024 * 1024
NONCE_SIZE = 16
MAX_MEDIA_ID_BYTES = 255
MAX_MAGIC_CANDIDATES = 64

PNG_CARRIER_MODE = "RGB"
RGB_CHANNEL_COUNT = 3
PNG_MEDIA_CONTEXT_FORMAT = ">II"
WAV_MEDIA_CONTEXT_FORMAT = ">HBIQ"
MAX_WAV_FRAME_BYTES = 64 * 1024 * 1024

FINGERPRINT_DISPLAY_PREFIX = "SHA256:"
